config/routes.rb
MyApp::Application.routes.draw do
resources :users
resources :sessions, only: [:new, :create, :destroy]
resources :statistics
resources :campaigns
  
  root  'static_pages#home'
  match '/signup', to: 'users#new', via:'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/dashboard', to: 'statistics#dashboard', via: 'get'
  match '/manager', to: 'campaigns#manager', via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

app/models/user.rb
class User < ActiveRecord::Base
	before_save {self.email =email.downcase}
	before_create :create_remember_token
	validates(:name, presence: true, length:{maximum: 50})
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates(:email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: true)
	validates(:password, length: {minimum: 6})
	has_secure_password
 def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
before_action :signed_in_user
  def manager
   
  end
  
  private
      def signed_in_user
      redirect_to signin_url, notice: "Please sign in." unless signed_in?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact  	
  end
end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  before_action :signed_in_user
  def dashboard
    
  end
  
  private
      def signed_in_user
      redirect_to signin_url, notice: "Please sign in." unless signed_in?
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:edit, :update]
  def show
  	@user =User.find(params[:id])  	
  end
  def new
  	@user =User.new
  end
  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  def create
  	@user =User.new(user_params)
  	if @user.save
  	  sign_in @user
  		flash[:success] = "Welcome to the Sample App!"
  		redirect_to @user
  	else
  		render 'new'
  	end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
    
    def signed_in_user
      redirect_to signin_url, notice: "Please sign in." unless signed_in?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title)
		base_title = "Ruby on Rails Tutorial Sample App"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}" 
		end
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end
  def signed_in?
    !current_user.nil?
  end
  def current_user=(user)
    @current_user = user
  end
  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end
  def sign_out
    current_user.update_attribute(:remember_token,User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/campaigns/manager.html.erb
<% provide(:title, "Campaign Manager") %>
    <div id="wrapper">
      <div id="page-wrapper">

        <div class="row">
          <div class="col-lg-12">
            <h1>Campaign Manager <small>Let's Strategize</small></h1>
            <ol class="breadcrumb">
              <li class="active"><i class="glyphicon glyphicon-calendar"></i> Campaigns</li>
            </ol>
            <div class="alert alert-success alert-dismissable">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              This is it. Setup Your campaigns and monitor your stats
            </div>
          </div>
        </div><!-- /.row -->
        <div class="row">
         <div class="col-lg-12">
            <div class="panel panel-primary">
              <div class="panel-heading">
                <h3 class="panel-title"><i class="glyphicon glyphicon-calendar"></i> All Campaigns</h3>
              </div>
              <div class="panel-body">        
              	<div class="table-responsive">
			<table class="table table-bordered table-hover tablesorter">			
			<thead>
				<tr>
			<th>Campaign name</th>
			<th>Start</th>
			<th>End</th>
			<th>Total Redeemed</th>
			<th>Total Valid </th>
			<th>Net Variance (Amt)</th>
			<th>Net Variance (%Amt%)</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>Campaign Samurai</td>
			<td>jan 6, 2014 8:14 am</td>
			<td>may 6, 2014 8:14 am</td>
			<td>100</td>
			<td>90</td>
			<td>90.00</td>
			<td>10%</td>
		</tr>
		<tr>
			<td>Campaign Ninja</td>
			<td>jan 8, 2014 8:14 am</td>
			<td>may 9, 2014 8:14 am</td>
			<td>1000</td>
			<td>90</td>
			<td>990.00</td>
			<td>1%</td>
		</tr>
	</tbody>
</table>
				</div>            
              </div>
            </div>
          </div>
        </div>

        <div class="row">
         <div class="col-lg-6">
            <div class="panel panel-primary">
              <div class="panel-heading">
                <h3 class="panel-title"><i class="glyphicon glyphicon-calendar"></i> Top 10 Campaigns</h3>
              </div>
              <div class="panel-body">        
              	<div class="table-responsive">
			<table class="table table-bordered table-hover tablesorter">			
			<thead>
				<tr>
			<th>Campaign name</th>
			<th>Start</th>
			<th>End</th>
			<th>Total Redeemed</th>
			<th>Total Valid </th>
			<th>Net Variance (Amt)</th>
			<th>Net Variance (%Amt%)</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>Campaign Samurai</td>
			<td>jan 6, 2014 8:14 am</td>
			<td>may 6, 2014 8:14 am</td>
			<td>100</td>
			<td>90</td>
			<td>90.00</td>
			<td>10%</td>
		</tr>
		<tr>
			<td>Campaign Ninja</td>
			<td>jan 8, 2014 8:14 am</td>
			<td>may 9, 2014 8:14 am</td>
			<td>1000</td>
			<td>90</td>
			<td>990.00</td>
			<td>1%</td>
		</tr>
	</tbody>
</table>
				</div>            
              </div>
            </div>
          </div>

         <div class="col-lg-6">
            <div class="panel panel-primary">
              <div class="panel-heading">
                <h3 class="panel-title"><i class="glyphicon glyphicon-calendar"></i> Bottom 10 Campaigns</h3>
              </div>
              <div class="panel-body">        
              	<div class="table-responsive">
			<table class="table table-bordered table-hover tablesorter">			
			<thead>
				<tr>
			<th>Campaign name</th>
			<th>Start</th>
			<th>End</th>
			<th>Total Redeemed</th>
			<th>Total Valid </th>
			<th>Net Variance (Amt)</th>
			<th>Net Variance (%Amt%)</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>Campaign Geisha</td>
			<td>jan 6, 2014 8:14 am</td>
			<td>may 6, 2014 8:14 am</td>
			<td>100</td>
			<td>90</td>
			<td>90.00</td>
			<td>10%</td>
		</tr>
		<tr>
			<td>Campaign Ronin</td>
			<td>jan 8, 2014 8:14 am</td>
			<td>may 9, 2014 8:14 am</td>
			<td>1000</td>
			<td>90</td>
			<td>990.00</td>
			<td>1%</td>
		</tr>
	</tbody>
</table>
				</div>            
              </div>
            </div>
          </div>
        </div>
        </div>
        </div><!-- /#page-wrapper -->

    </div>
  <script>
  	$(document).ready(function() {
	// call the tablesorter plugin
	$("table").tablesorter({
		// sort on the first column and third column, order asc
		sortList: [[0,0],[2,0]]
	});
}); 
  </script>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://tranquil-plains-4192.herokuapp.com">AdVertz by H-D Lab.</a>
    
  </small>
  <nav>
    <ul>
      <li><%= link_to '<i class="glyphicon glyphicon-info-sign""></i> About'.html_safe, about_path %></li>
      <li><%= link_to '<i class="glyphicon glyphicon-phone-alt"></i> Contact'.html_safe, contact_path %></li>
      <li><i class="glyphicon glyphicon-globe"></i><a href="http://news.railstutorial.org/"> News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse navbar-fixed-top bs-docs-nav" role="banner">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "AdVertz", root_path, class: "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          	<li><%= link_to '<i class="glyphicon glyphicon-home"></i> Home'.html_safe, root_path %></li>
          	<li><%= link_to '<i class="glyphicon glyphicon-question-sign"></i> Help'.html_safe, help_path %></li>
		<% if signed_in? %>
					<li><%= link_to '<i class="glyphicon glyphicon-dashboard"></i> Dashboard'.html_safe, dashboard_path %></li>
                	<li><%= link_to '<i class="glyphicon glyphicon-book"></i> Profile'.html_safe, current_user %></li>
                	<li><%= link_to '<i class="glyphicon glyphicon-edit"></i> Settings'.html_safe, edit_user_path(current_user) %></li>
                	<li><a href="#"><i class="glyphicon glyphicon-user"></i> Manage Users</a></li> 
                	<li><%= link_to '<i class="glyphicon glyphicon-calendar"></i> Campaign Manager'.html_safe, manager_path %></li>           
                	<li><%= link_to '<i class="glyphicon glyphicon-off"></i> Sign out'.html_safe, signout_path, method: "delete" %></li>
          	<% else %>
            		<li><%= link_to '<i class="glyphicon glyphicon-off"></i> Sign in'.html_safe, signin_path %></li>
          	<% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width , initial-scale=1.0" />
<title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all",
                                            "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
  <body>
<%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>

  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<!DOCTYPE html>
<html>
  <head>
    <title>AdVertz | <%= yield(:title) %></title>
  </head>
  <body>
  <div id="wrapper">
      <div id="page-wrapper">

        <div class="row">
          <div class="col-lg-12">
            <h1>About Us <small>Who we are</small></h1>
            <ol class="breadcrumb">
              <li class="active"><i class="glyphicon glyphicon-info-sign"></i> Company Profile</li>
            </ol>
			    <p>
			      One stop Advertising solution is in your hands. work with us to make your product known
			    </p>
          </div>
        </div>
  </body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Help') %>
<!DOCTYPE html>
<html>
  <head>
    <title>AdVertz | <%= yield(:title) %></title>
  </head>
  <body>
  <div id="wrapper">
      <div id="page-wrapper">

        <div class="row">
          <div class="col-lg-12">
            <h1>Contact Us <small>Knock Our Door</small></h1>
            <ol class="breadcrumb">
              <li class="active"><i class="glyphicon glyphicon-phone-alt"></i> Contact Us</li>
            </ol>
			    <p>
			      Site under construction
			    </p>
          </div>
        </div>
  </body>
</html>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<!DOCTYPE html>
<html>
  <head>
    <title>AdVertz | <%= yield(:title) %></title>
  </head>
  <body>
  <div id="wrapper">
      <div id="page-wrapper">

        <div class="row">
          <div class="col-lg-12">
            <h1>Help <small>Feeling Lost?</small></h1>
            <ol class="breadcrumb">
              <li class="active"><i class="glyphicon glyphicon-question-sign"></i> FAQ</li>
            </ol>
			    <p>
			      Site under construction
			    </p>
          </div>
        </div>
  </body>
</html>

app/views/static_pages/home.html.erb
<% provide(:title) %>
<div class="bs-header" id="content">
	<div class="container">
  <h1>Welcome to AdVertz</h1>

  <h2>
    Future of Advertising is here
    <a href="http://railstutorial.org/">AdVertz..</a>
  </h2>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>
</div>
<div class="row-fluid">
    <div class="span4">
        <h4>Our Clients</h4>
        <p>Hello These are our clients. <a href="#">Click here</a>.</p>
        <a href="#" class="btn btn-primary"><i class="icon-heart icon-white"></i> Our Clients</a>
    </div>
    <div class="span4">
        <h4>Our Clients</h4>
        <p>Hello These are our clients. <a href="#">Click here</a>.</p>
        <a href="#" class="btn btn-primary"><i class="icon-music icon-white"></i> Our Clients</a>
    </div>
    <div class="span4">
        <h4>Our Clients</h4>
        <p>Hello These are our clients. <a href="#">Click here</a>.</p>
        <a href="#" class="btn btn-primary"><i class="icon-file icon-white"></i> Our Clients</a>
    </div>
    </div>

<%#= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/statistics/dashboard.html.erb
<% provide(:title, "Dashboard") %>
  <div id="wrapper">
      <div id="page-wrapper">

        <div class="row">
          <div class="col-lg-12">
            <h1>Dashboard <small>Statistic</small></h1>
            <ol class="breadcrumb">
              <li class="active"><i class="glyphicon glyphicon-dashboard"></i> Overview</li>
            </ol>
            <div class="alert alert-success alert-dismissable">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              Welcome to Advertz Dashboard. Detailed view of your statistic.Real time..
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-3">
            <div class="panel panel-info">
              <div class="panel-heading">
                <div class="row">
                  <div class="col-xs-6">
                    <i class="glyphicon glyphicon-play-circle announcement-heading"></i>
                  </div>
                  <div class="col-xs-6 text-right">
                    <p class="announcement-heading">456</p>
                    <p class="announcement-text">Campaigns</p>
                  </div>
                </div>
              </div>
              <a href="#">
                <div class="panel-footer announcement-bottom">
                  <div class="row">
                    <div class="col-xs-6">
                      View Campaigns
                    </div>
                    <div class="col-xs-6 text-right">
                      <i class="glyphicon glyphicon-circle-arrow-right"></i>
                    </div>
                  </div>
                </div>
              </a>
            </div>
          </div>
          <div class="col-lg-3">
            <div class="panel panel-warning">
              <div class="panel-heading">
                <div class="row">
                  <div class="col-xs-6">
                    <i class="glyphicon glyphicon-ok announcement-heading"></i>
                  </div>
                  <div class="col-xs-6 text-right">
                    <p class="announcement-heading">12</p>
                    <p class="announcement-text">To-Do Items</p>
                  </div>
                </div>
              </div>
              <a href="#">
                <div class="panel-footer announcement-bottom">
                  <div class="row">
                    <div class="col-xs-6">
                      Complete Tasks
                    </div>
                    <div class="col-xs-6 text-right">
                      <i class="glyphicon glyphicon-circle-arrow-right"></i>
                    </div>
                  </div>
                </div>
              </a>
            </div>
          </div>
          <div class="col-lg-3">
            <div class="panel panel-danger">
              <div class="panel-heading">
                <div class="row">
                  <div class="col-xs-6">
                    <i class="glyphicon glyphicon-warning-sign announcement-heading"></i>
                  </div>
                  <div class="col-xs-6 text-right">
                    <p class="announcement-heading">18</p>
                    <p class="announcement-text">Complaints</p>
                  </div>
                </div>
              </div>
              <a href="#">
                <div class="panel-footer announcement-bottom">
                  <div class="row">
                    <div class="col-xs-6">
                      View Complaints
                    </div>
                    <div class="col-xs-6 text-right">
                      <i class="glyphicon glyphicon-circle-arrow-right"></i>
                    </div>
                  </div>
                </div>
              </a>
            </div>
          </div>
          <div class="col-lg-3">
            <div class="panel panel-success">
              <div class="panel-heading">
                <div class="row">
                  <div class="col-xs-6">
                    <i class="glyphicon glyphicon-bullhorn announcement-heading"></i>
                  </div>
                  <div class="col-xs-6 text-right">
                    <p class="announcement-heading">56</p>
                    <p class="announcement-text">Message</p>
                  </div>
                </div>
              </div>
              <a href="#">
                <div class="panel-footer announcement-bottom">
                  <div class="row">
                    <div class="col-xs-6">
                      View Messages
                    </div>
                    <div class="col-xs-6 text-right">
                      <i class="glyphicon glyphicon-circle-arrow-right"></i>
                    </div>
                  </div>
                </div>
              </a>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12">
            <div class="panel panel-primary">
              <div class="panel-heading">
                <h3 class="panel-title"><i class="glyphicon glyphicon-dashboard"></i> Today's Statistic</h3>
              </div>
              <div class="panel-body">
                <div id="myfirstchart" style="height: 250px;"></div>         
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-8">
            <div class="panel panel-primary">
              <div class="panel-heading">
                <h3 class="panel-title"><i class="glyphicon glyphicon-dashboard"></i> Campaign Type Effectiveness</h3>
              </div>
              <div class="panel-body">   
              	<div id="mysecondchart" style="height: 250px;"></div>                  
              </div>
            </div>
          </div>
          
         <div class="col-lg-4">
            <div class="panel panel-primary">
              <div class="panel-heading">
                <h3 class="panel-title"><i class="glyphicon glyphicon-dashboard"></i> User Trends</h3>
              </div>
              <div class="panel-body">
                <div id="mydonut" style="height: 250px;"></div>         
              </div>
            </div>
          </div>
        </div>
        
        <div class="row">
         <div class="col-lg-12">
            <div class="panel panel-primary">
              <div class="panel-heading">
                <h3 class="panel-title"><i class="glyphicon glyphicon-calendar"></i> All Campaigns Stats</h3>
              </div>
              <div class="panel-body">        
              	<div class="table-responsive">
			<table class="table table-bordered table-hover tablesorter">			
			<thead>
				<tr>
			<th>Campaign name</th>
			<th>Start</th>
			<th>End</th>
			<th>Total Redeemed</th>
			<th>Total Valid </th>
			<th>Net Variance (Amt)</th>
			<th>Net Variance (%Amt%)</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>Campaign Samurai</td>
			<td>jan 6, 2014 8:14 am</td>
			<td>may 6, 2014 8:14 am</td>
			<td>100</td>
			<td>90</td>
			<td>90.00</td>
			<td>10%</td>
		</tr>
		<tr>
			<td>Campaign Ninja</td>
			<td>jan 8, 2014 8:14 am</td>
			<td>may 9, 2014 8:14 am</td>
			<td>1000</td>
			<td>90</td>
			<td>990.00</td>
			<td>1%</td>
		</tr>
	</tbody>
</table>
				</div>            
              </div>
            </div>
          </div>
        </div>
   	
</body>
 </div><!-- /#page-wrapper -->

 </div>
<script>
	new Morris.Line({
  // ID of the element in which to draw the chart.
  element: 'myfirstchart',
  // Chart data records -- each entry in this array corresponds to a point on
  // the chart.
  data: [
    { year: '2008', value: 20 },
    { year: '2009', value: 10 },
    { year: '2010', value: 5 },
    { year: '2011', value: 5 },
    { year: '2012', value: 20 }
  ],
  // The name of the data record attribute that contains x-values.
  xkey: 'year',
  // A list of names of data record attributes that contain y-values.
  ykeys: ['value'],
  // Labels for the ykeys -- will be displayed when you hover over the
  // chart.
  labels: ['Value']
});
</script>
<script>
	new Morris.Bar({
  // ID of the element in which to draw the chart.
  element: 'mysecondchart',
  // Chart data records -- each entry in this array corresponds to a point on
  // the chart.
  data: [
    { year: '2008', value: 20 },
    { year: '2009', value: 10 },
    { year: '2010', value: 5 },
    { year: '2011', value: 5 },
    { year: '2012', value: 20 }
  ],
  // The name of the data record attribute that contains x-values.
  xkey: 'year',
  // A list of names of data record attributes that contain y-values.
  ykeys: ['value'],
  // Labels for the ykeys -- will be displayed when you hover over the
  // chart.
  labels: ['Value']
});

  	$(document).ready(function() {
	// call the tablesorter plugin
	$("table").tablesorter({
		// sort on the first column and third column, order asc
		sortList: [[0,0],[2,0]]
	});
}); 

Morris.Donut({
  element: 'mydonut',
  data: [
    {label: "Download Sales", value: 12},
    {label: "In-Store Sales", value: 30},
    {label: "Mail-Order Sales", value: 20}
  ]
});
</script>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>